Playlist/urls.py
from django.conf.urls import patterns, url, include
from rest_framework.routers import DefaultRouter
from rest_framework import routers, serializers, viewsets
from Playlist import views

router = DefaultRouter()
router.register(r'playlist', views.PlaylistViewSet)
router.register(r'users', views.UserViewSet)

urlpatterns = patterns("", 
    url(r"^$", views.overview, name="overview"),
    url(r"^register", views.register_view, name="register"),
    url(r"^login", views.login_view, name="login"),
    url(r"^logout", views.logout_view, name="logout"),
    url(r"^settings", views.settings_view, name="settings"),
    url(r"^(?P<user_name>\w+)/$", views.user_view, name="user"),
    url(r"^(?P<user_name>\w+)/(?P<playlist_name>\w+)/$", views.playlist_view, name="playlistdetails"),
    url(r'^api/', include(router.urls)),
)

mysite/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import patterns, include, url
from django.views.generic.base import RedirectView

from django.contrib import admin

from RestFramework import views

admin.autodiscover()

urlpatterns = patterns('',
    url(r'^admin/doc/', include('django.contrib.admindocs.urls')),
    url(r'^admin/', include(admin.site.urls)),

    url(r'^favicon\.ico$', RedirectView.as_view(url='/media/favicon.ico')), 

    url(r"^polls/", include("polls.urls")),
    url(r"^playlist/", include("Playlist.urls", app_name="PlaylistApp", namespace="Playlist")),
    
    url(r"^website/", include("ownWebsite.urls", app_name="ownWebsite", namespace="ownWebsite")),

    url(r"^api-auth/", include("rest_framework.urls", namespace="rest_framework")),
) 

if settings.DEBUG:
    # urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += patterns('django.views.static', 
            (r'media/(?P<path>.*)', 
            'serve', 
            {'document_root': settings.MEDIA_ROOT}), )

polls/urls.py
from django.conf.urls import patterns, url
from mysite import settings

from polls import views

urlpatterns = patterns("", 
        url(r"^$", views.index, name="index"),
	url(r"^sound$", views.sound, name="sound")
)

Playlist/models.py
from django.db import models
from django.contrib.auth.models import User

class Playlist(models.Model):
    name = models.CharField(max_length=200)
    pub_date = models.DateTimeField("date published", auto_now_add=True)

    owner = models.ForeignKey("UserProfile")

    def __unicode__(self):
        return self.name 

class Track(models.Model):
    playlist = models.ForeignKey(Playlist)
    title = models.CharField(max_length=200)
    url = models.CharField(max_length=200)
    plattform = models.IntegerField()
    # 0 Youtube
    # 1 Soundcloud
    pub_date = models.DateTimeField("date published")

    def __unicode__(self):
        return self.title 

class UserProfile(models.Model):
    user = models.OneToOneField(User)

    soundcloud = models.CharField(max_length=200, blank=True)
    youtube = models.CharField(max_length=200, blank=True)

    picture = models.ImageField(upload_to='profile_images', blank=True)

    def __unicode__(self):
        return self.user.username

Playlist/forms.py
from django import forms
from django.contrib.auth.models import User
from Playlist.models import Track, Playlist, UserProfile


class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())
    username = forms.CharField(help_text="")

    class Meta:
        model = User
        fields = ('username', 'email', 'password')

class UserProfileForm(forms.ModelForm):
    soundcloud = forms.CharField(required=False)
    youtube = forms.CharField(required=False)
    picture = forms.ImageField(help_text="", required=False)

    class Meta:
        model = UserProfile
        fields = ('picture', 'youtube', 'soundcloud', )

Playlist/views.py
from django.shortcuts import render, render_to_response, get_object_or_404, redirect
from django.core.urlresolvers import reverse
from django.core.exceptions import ObjectDoesNotExist
from django.http import HttpResponse, HttpResponseRedirect
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.models import User
from django.utils import timezone

from Playlist.models import *
from Playlist.forms import UserProfileForm, UserForm
from Playlist.serializers import PlaylistSerializer, UserSerializer
# from snippets.permissions import IsOwnerOrReadOnly

from rest_framework import generics, permissions, renderers, viewsets
from rest_framework.decorators import api_view, detail_route
from rest_framework.response import Response
from rest_framework.reverse import reverse

def overview(request):
    name = request.POST.get("name")

    if name in ['settings', 'user', 'register', 'login', 'logout']:
        return HttpResponseRedirect(reverse('Playlist:overview'))

    if name:
        playlist = Playlist.objects.get_or_create(name=name, owner=request.user.userprofile)[0]
        playlist.save()
        # playlist.userprofile_set.add(request.user.userprofile)

    allplaylists = Playlist.objects.all()

    return render(request, "Playlist/overview.html", {"playlists": allplaylists, "popupmessages": []})

def playlist_view(request, user_name="", playlist_name=""):
    u = request.POST.get("url")
    t = request.POST.get("title")
    p = request.POST.get("plattform")

    if t and u and p:
        track = Track(title=t,
                plattform=p,
                url=u,
                pub_date=timezone.now(), 
                playlist=Playlist.objects.get(name=playlist_name))
        track.save()

    delt = request.POST.get("deltitle")
    if delt: 
        Track.objects.get(id=delt).delete()

    p = get_object_or_404(Playlist, name=playlist_name)

    editable = False
    if request.user.is_authenticated() and request.user.id == p.owner_id:
        editable = True
    
    return render(request, "Playlist/playlistdetails.html", {"playlist":p, 'CanEdit': editable})

def user_view(request, user_name=""):

    if not user_name:
        return render(request, "Playlist/user_overview.html", {'users': User.objects.all()[:5]})

    try:
        user = User.objects.get(username=user_name)

        return render(request, "Playlist/user.html", {})

    except ObjectDoesNotExist:
        user = None
        
    return render(request, "Playlist/user.html", {})

def settings_view(request):

    if request.user.is_authenticated():

        user_form = UserForm(instance=request.user)
        profile_form = UserProfileForm(instance=request.user.userprofile)

        return render(request, "Playlist/settings.html", {'user_form': user_form, 'profile_form': profile_form})

    else:
        return render(request, "Playlist/settings.html", {})

def register_view(request):
    registered = False

    if request.method == 'POST':
        user_form = UserForm(data=request.POST)
        profile_form = UserProfileForm(data=request.POST)

        if user_form.is_valid() and profile_form.is_valid():
            user = user_form.save()

            user.set_password(user.password)
            user.save()

            profile = profile_form.save(commit=False)
            profile.user = user

            if 'picture' in request.FILES:
                profile.picture = request.FILES['picture']

            profile.save()

            registered = True

            user = authenticate(username=user.username, password=request.POST.get('password'))

            if user:
                if user.is_active:
                    login(request, user)
                    return HttpResponseRedirect(reverse('Playlist:overview'))

        else:
            print user_form.errors, profile_form.errors
    else:
        user_form = UserForm()
        profile_form = UserProfileForm()

    return render(request,
            'Playlist/register.html',
            {'user_form': user_form, 'profile_form': profile_form, 'registered': registered})

def logout_view(request):
    logout(request)
    return HttpResponseRedirect(reverse('Playlist:overview'))

def login_view(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']

        user = authenticate(username=username, password=password)

        if user:
            if user.is_active:
                login(request, user)
                return HttpResponseRedirect(reverse('Playlist:overview'))
            else:
                return HttpResponse('Account not active yet')
        else:
            print "Invalid login details: {0}, {1}".format(username, password)
            return render(request, 'Playlist/login.html', {'error': True})

    else:
        return render(request, 'Playlist/login.html', {})


class UserViewSet(viewsets.ReadOnlyModelViewSet):
    queryset = User.objects.all()
    serializer_class = UserSerializer

class PlaylistViewSet(viewsets.ModelViewSet):
    queryset = Playlist.objects.all()
    serializer_class = PlaylistSerializer
    # permission_classes = (permissions.IsAuthenticatedOrReadOnly, IsOwnerOrReadOnly, )

    # @detail_route(renderer_classes=[renderers.StaticHTMLRenderer])
    # def highlight(self, request, *args, **kwargs):
    #     snippet = self.get_object()
    #     return Response(snippet.highlighted)

    # def perform_create(self, serializer):
    #     serializer.save(owner=self.request.user)

# @api_view(('GET', ))
# def api_root(request, format=None):
#     return Response({
#         'users': reverse('user-list', request=request, format=format),
#         'snippets': reverse('snippet-list', request=request, format=format)})

Playlist/templates/Playlist/base.html
{% load staticfiles %}
<html>
  <head>
    <title>{% block title %}Playomat{% endblock %}</title>
    <meta http-equiv="content-type" content="text/html; charset=UTF-8" />
    <link rel="stylesheet" type="text/css" href="{% static "Playlist/normalize.css" %}">
    <link rel="stylesheet" type="text/css" href="{% static "Playlist/bootstrap.min.css" %}">
    <link rel="stylesheet" type="text/css" href="{% static "Playlist/jumbotron-narrow.css" %}">
    <!-- <link rel="stylesheet" type="text/css" href="{% static "Playlist/skeleton.css" %}"> -->
    <link rel="stylesheet" type="text/css" href="{% static "Playlist/style.css" %}">
    {% block imports %}{% endblock %}
  </head>
  <body>
    <div class="container">
      <div class="header">
        <nav>
          <ul class="nav nav-pills pull-right">
            {% block navigation %}
            {% if user.is_authenticated %}
            <li role="presentation"><h4>Hi {{ user.username }}!</h4></li>
            <li role="presentation"><a href="settings"><img style="height: 40px; margin-left: 10px;" src='{{ MEDIA_URL }}{{ user.userprofile.picture.name }}' /></a></li>
            <li role="presentation"><a href="{% url 'Playlist:logout' %}">Logout</a></li>
            {% else %}
            <li role="presentation"><a href="{% url 'Playlist:register' %}">Register now</a></li>
            <li role="presentation"><a href="{% url 'Playlist:login' %}">Login</a></li>
            {% endif %}
            {% endblock %}
          </ul>
        </nav>
        <h3 class="text-muted"><a href="{% url 'Playlist:overview' %}">Playomat</a></h3>
      </div>
      {% block content %}{% endblock %}
      <footer class="footer">
        <p>&copy; Adrian Bartnik 2015</p>
      </footer>
    </div>
  </body>
</html>

Playlist/templates/Playlist/login.html
{% extends "Playlist/base.html" %}

{% block title %}Login{% endblock %} 
            
{% block navigation %}
{% endblock %}

{% block content %}

<h3>Login to Playomat</h3>

{% if error %}
<h3 style="color: red;">Invalid login. Try again.</h3>
{% endif %}

<form id="loginform" method="post" action="{% url 'Playlist:login' %}">
  {% csrf_token %}
  <div class="row">
    <div class="col-md-4">Username: <input type="text" name="username" value=""  /></div>
    <div class="col-md-4">Password: <input type="password" name="password" value=""  /></div>
    <div class="col-md-4"><input class="btn btn-default" type="submit" value="Login" /></div>
  </div>
</form>
<div class="text-center">
  <a href="{% url 'Playlist:overview' %}" style="font-size: 20px;">Back to the homepage</a>
</div>
{% endblock %}

Playlist/templates/Playlist/overview.html
{% extends "Playlist/base.html" %}

{% block content %}
  {% for pm in popupmessages %}
    <h3>{{ pm }}</h3>
  {% endfor %}
  <h3>Share playlists with you friends with this simple website!</h3>
<div class="list-group" id="AvailablePlaylists">
  <h2 class="text-center" id="AvaPlaylistHeading">Available Playlists</h2>
    {% for p in playlists %}
      <a class="list-group-item" href="{% url 'Playlist:playlistdetails' p.owner.user.username p.name %}"><h3>{{ p.name }}</h3></a>
    {% endfor %}
</div>
  {% if user.is_authenticated %}
    <div class="text-center center-block" id="addTitle">
      <form action="{% url 'Playlist:overview' %}" method="post">
        {% csrf_token %}
        <label for="playlistname">Create new playlist</label>
        <input type="text" name="name" size=50 id="playlistname" value="Your Name" />
        <input class="btn btn-default" type="submit" value="Create" />
      </form>
    </div>
  {% endif %}
{% endblock %}

Playlist/templates/Playlist/playlistdetails.html
{% extends "Playlist/base.html" %}

{% block title %}Playlist Details{% endblock %}

{% block imports %}
<script src="http://connect.soundcloud.com/sdk.js"></script>
<script src="https://w.soundcloud.com/player/api.js"></script>
<script src="https://www.youtube.com/iframe_api"></script>
<script type="text/javascript" src="{{ STATIC_URL }}Playlist/jquery.js" %}></script>
<script type="text/javascript" src="{{ STATIC_URL }}Playlist/PlaylistDetails.js" %}></script>
{% endblock %}

{% block content %}
<div class="text-center">
  <div id="title">
    <h1>{{ playlist.name }}</h1>
  </div>
{% if CanEdit %}
<div id="addTitle">
  <form action="{% url 'Playlist:playlistdetails' playlist.owner.user.username playlist.name %}" method="post">
    {% csrf_token %}
    <label for="new_song">New song title</label>
    <input type="text" name="url" size=50 id="songURL" value="" />
    <input type="hidden" name="title" id="songTitle" value="" />
    <input type="hidden" name="plattform" id="plattform" value="" />
    <input type="submit" class="btn btn-default" value="Add" />
  </form>
</div>
{% endif %}
</div>

<div id="allTracks">
    <span id="playAll" class="btn btn-default">
      Play all
    </span>
  <ul class="list-group">
    {% for t in playlist.track_set.all %}
    <li class="list-group-item track clearfix" plattform="{{ t.plattform }}" listitem="{{ forloop.counter0 }}" url="{{ t.url }}">
      <div class="pull-left trackText"><h3>{{ t.title }}</h3></div>
      <div class="pull-right">
        <form action="{% url 'Playlist:playlistdetails' p.owner.user.username playlist.name %}" method="post">
        {% csrf_token %}
        <input type="hidden" name="deltitle" value="{{ t.id }}" />
        <input type="submit" class="btn btn-default" id="DeleteButton" value="Delete">
          <!-- <img src="{{ STATIC_URL }}Playlist/button.png" %}" id="DeleteButtonImage" alt="submit"> -->
      </form>
      </div>
    </li>
    {% endfor %}
  </ul>
</div>

<div id=player> 
  <div id="scplayer"></div>
  <div id="ytplayer"></div>
</div>
{% endblock %}

Playlist/templates/Playlist/register.html
{% extends "Playlist/base.html" %}

{% block content %}

{% if registered %}
<strong>Thank you for registering</strong>
<a href='{% url "Playlist:overview" %}'>To startpage</a>
{% else %}
<h3>Register here</h3>

<form id="user_form" method="post" action="{% url 'Playlist:register' %}" enctype="multipart/form-data">
  {% csrf_token %}

  {{ user_form.as_p }}
  {{ profile_form.as_p }}

  <input type="submit" class="btn btn-default" name"submit" value="register" />
</form>
{% endif %}

{% endblock %}

Playlist/templates/Playlist/settings.html
{% extends "Playlist/base.html" %}

{% block content %}

{% if user.is_authenticated %}
<div class="text-center center-block" id="addTitle">
  <form id="user_form" method="post" action="{% url 'Playlist:user' user.username %}" enctype="multipart/form-data">
    {% csrf_token %}

    {{ user_form.as_p }}
    {{ profile_form.as_p }}

    <input type="submit" class="btn btn-default" name"submit" value="apply" />
  </form>
</div>
{% else %}
  <h3>You are not logged in!</h3>
{% endif %}

{% endblock %}

Playlist/templates/Playlist/user.html
{% extends "Playlist/base.html" %}

{% block content %}

{% if user.is_authenticated %}
<div class="text-center center-block" id="addTitle">
  <h3>{{ user.username }}</h3>
  <h3>{{ user.userprofile.picture }}</h3>
  {% for playlist in user.userprofile.playlists.all %}
    <h3>{{ playlist }}</h3>
  {% endfor %}
</div>
{% else %}
  <h3>You are not logged in!</h3>
{% endif %}

{% endblock %}

Playlist/templates/Playlist/user_overview.html
{% extends "Playlist/base.html" %}

{% block content %}

<div class="text-center center-block" id="addTitle">
  {% for u in users %}
    <h3>{{ u.username }}</h3>
    <h3>{{ u.userprofile.picture }}</h3>
  {% endfor %}
</div>

{% endblock %}