mysite/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import patterns, include, url
from django.views.generic.base import RedirectView

from django.contrib import admin

from RestFramework import views

admin.autodiscover()

urlpatterns = patterns('',
    url(r'^admin/doc/', include('django.contrib.admindocs.urls')),
    url(r'^admin/', include(admin.site.urls)),

    url(r'^favicon\.ico$', RedirectView.as_view(url='/media/favicon.ico')), 

    url(r"^polls/", include("polls.urls")),
    url(r"^playlist/", include("Playlist.urls", app_name="PlaylistApp", namespace="Playlist")),
    
    url(r"^website/", include("ownWebsite.urls", app_name="ownWebsite", namespace="ownWebsite")),

    url(r"^api-auth/", include("rest_framework.urls", namespace="rest_framework")),
) 

if settings.DEBUG:
    # urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += patterns('django.views.static', 
            (r'media/(?P<path>.*)', 
            'serve', 
            {'document_root': settings.MEDIA_ROOT}), )

ownWebsite/urls.py
from django.conf.urls import patterns, url

from ownWebsite import views

urlpatterns = patterns("", 
        url(r"^$", views.index, name="index"),
        url(r"^blog$", views.blog, name="blog"),
        url(r"^aboutme$", views.aboutme, name="aboutme"),
        url(r"^impressum$", views.impressum, name="impressum"),
        url(r"^projects$", views.projects, name="projects"),
        url(r"^travel$", views.travel, name="travel"),
        # url(r"^image", views.image, name="image"),
        # url(r"^sound", views.sound, name="sound"),
        # url(r"^change", views.change, name="change"),
        # url(r"^(?P<playlist_title>\w+)/$", views.playlistdetails, name="playlistdetails"),
)

polls/urls.py
from django.conf.urls import patterns, url
from mysite import settings

from polls import views

urlpatterns = patterns("", 
        url(r"^$", views.index, name="index"),
	url(r"^sound$", views.sound, name="sound")
)

ownWebsite/models.py
from django.db import models

# Create your models here.

class Post(models.Model):
    title = models.CharField(max_length=200)
    text = models.TextField()
    pub_date = models.DateTimeField("date published")

    def __unicode__(self):
        # return unicode(self.title + " " + self.pub_date)
        return self.title

ownWebsite/views.py
from django.shortcuts import render, render_to_response, get_object_or_404
from django.http import HttpResponse
from django.utils import timezone

from ownWebsite.models import *

def index(request):
    return render_to_response("ownWebsite/Index.html")

def aboutme(request):
    return render_to_response("ownWebsite/AboutMe.html")

def impressum(request):
    return render_to_response("ownWebsite/Impressum.html")

def projects(request):
    return render_to_response("ownWebsite/Projects.html")

def travel(request):
    return render_to_response("ownWebsite/Travel.html")

def blog(request):
    if request.GET.get("all"): 
        p = Post.objects.all().order_by('pub_date')
        print "LOLZ"
    else:
        p = Post.objects.all().order_by('pub_date').reverse()[0:3]
    return render(request, "ownWebsite/Blog.html", {"posts": p, "all": request.GET.get("all")})

# def overview(request):
#     p = request.POST.get("name")
#     if p:
#         np = Playlist(pub_date=timezone.now(), title=p)
#         np.save()
#     a = Playlist.objects.all()
#     return render(request, "Playlist/overview.html", {"playlists":a})

# def playlistdetails(request, playlist_title=""):
#     u = request.POST.get("url")
#     t = request.POST.get("title")
#     p = request.POST.get("plattform")
#     if t and u and p:
#         track = Track(title=t,
#                 plattform=p,
#                 url=u,
#                 pub_date=timezone.now(), 
#                 playlist=Playlist.objects.get(title=playlist_title))
#         track.save()

#     delt = request.POST.get("deltitle")
#     if delt: 
#         Track.objects.get(id=delt).delete()

#     p = get_object_or_404(Playlist, title=playlist_title)
#     return render(request, "Playlist/playlistdetails.html", {"playlist":p})

ownWebsite/templates/ownWebsite/AboutMe.html
{% extends "ownWebsite/base.html" %}
{% load static %}

{% block title %}Blog{% endblock %}

{% block content %}
<p>
Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet.   
<img id="profileimage" 
     src="{% static "ownWebsite/ProfileImage.jpg" %}" 
     alt="ProfileImage">
</p>
<p>
Duis autem vel eum iriure dolor in hendrerit in vulputate velit esse molestie consequat, vel illum dolore eu feugiat nulla facilisis at vero eros et accumsan et iusto odio dignissim qui blandit praesent luptatum zzril delenit augue duis dolore te feugait nulla facilisi. Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat.   
</p>

<p>
Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat. Duis autem vel eum iriure dolor in hendrerit in vulputate velit esse molestie consequat, vel illum dolore eu feugiat nulla facilisis at vero eros et accumsan et iusto odio dignissim qui blandit praesent luptatum zzril delenit augue duis dolore te feugait nulla facilisi.   
</p>

<p>
Nam liber tempor cum soluta nobis eleifend option congue nihil imperdiet doming id quod mazim placerat facer.
</p>
{% endblock %}

ownWebsite/templates/ownWebsite/Blog.html
{% extends "ownWebsite/base.html" %}

{% block title %}Blog{% endblock %}

{% block content %}

      {% for p in posts %}
        <h1>{{ p.title }}</h1>
        <h6>{{ p.pub_date }}</h6>
        <h4>{{ p.text }}</h4>
      {% endfor %}

      {% if not all %}
        <a href={% url 'ownWebsite:blog' %}?all=true>My older posts</a>
      {% endif %}

{% endblock %}

ownWebsite/templates/ownWebsite/Impressum.html
{% extends "ownWebsite/base.html" %}

{% block title %}Blog{% endblock %}

{% block content %}
<h1>Impressum</h1>
<h2>Angaben gemäß § 5 TMG:</h2>
<p>Adrian Bartnik<br />
Friebestrasse 4<br />
33332 Gütersloh<br />
Germany
</p>
<h2>Kontakt:</h2>
<table><tr>
    <tr><td>E-Mail:</td>
      <td>
        <script type="text/javascript">
name = "&#105;&#110;&#102;&#111;";
domain = "&#064;&#097;&#100;&#114;&#105;&#097;&#110;&#098;&#97;&#114;&#116;&#110;&#105;&#107;&#46;&#100;&#101;";
document.write("<a href='mailto:" + name + domain + "'>" + name + domain + "</a>");
        </script>
        <noscript>Um alle Inhalte anzuzeigen aktivieren Sie bitte JavaScript in Ihrem Browser!</noscript>
      </td>
    </tr></table>
    <h1>Haftungsausschluss</h1>
    <p><strong>Haftung für Inhalte</strong></p> <p>Als Diensteanbieter bin ich gemäß § 7 Abs.1 TMG für eigene Inhalte auf diesen Seiten nach den allgemeinen Gesetzen verantwortlich. Nach §§ 8 bis 10 TMG bin ich als Diensteanbieter jedoch nicht verpflichtet, übermittelte oder gespeicherte fremde Informationen zu überwachen oder nach Umständen zu forschen, die auf eine rechtswidrige Tätigkeit hinweisen. Verpflichtungen zur Entfernung oder Sperrung der Nutzung von Informationen nach den allgemeinen Gesetzen bleiben hiervon unberührt. Eine diesbezügliche Haftung ist jedoch erst ab dem Zeitpunkt der Kenntnis einer konkreten Rechtsverletzung möglich. Bei Bekanntwerden von entsprechenden Rechtsverletzungen werde ich diese Inhalte umgehend entfernen.</p> 
    <p><strong>Haftung für Links</strong></p> 
    <p>Unser Angebot enthält Links zu externen Webseiten Dritter, auf deren Inhalte wir keinen Einfluss haben. Deshalb können wir für diese fremden Inhalte auch keine Gewähr übernehmen. Für die Inhalte der verlinkten Seiten ist stets der jeweilige Anbieter oder Betreiber der Seiten verantwortlich. Die verlinkten Seiten wurden zum Zeitpunkt der Verlinkung auf mögliche Rechtsverstöße überprüft. Rechtswidrige Inhalte waren zum Zeitpunkt der Verlinkung nicht erkennbar. Eine permanente inhaltliche Kontrolle der verlinkten Seiten ist jedoch ohne konkrete Anhaltspunkte einer Rechtsverletzung nicht zumutbar. Bei Bekanntwerden von Rechtsverletzungen werden wir derartige Links umgehend entfernen.</p> 
    <p><strong>Urheberrecht</strong></p> 
    <p>Die durch mich erstellten Inhalte und Werke auf diesen Seiten unterliegen dem deutschen Urheberrecht. Die Vervielfältigung, Bearbeitung, Verbreitung und jede Art der Verwertung außerhalb der Grenzen des Urheberrechtes bedürfen der schriftlichen Zustimmung des jeweiligen Autors bzw. Erstellers. Downloads und Kopien dieser Seite sind nur für den privaten, nicht kommerziellen Gebrauch gestattet. Soweit die Inhalte auf dieser Seite nicht von mir erstellt wurden, werden die Urheberrechte Dritter beachtet. Insbesondere werden Inhalte Dritter als solche gekennzeichnet. Sollten Sie trotzdem auf eine Urheberrechtsverletzung aufmerksam werden, bitte ich um einen entsprechenden Hinweis. Bei Bekanntwerden von Rechtsverletzungen werde ich derartige Inhalte umgehend entfernen.</p>

<p><strong>Bildnachweise</strong></p> 
<p><strong>Katze</strong>:
DoriPili - Cats_S - https://www.flickr.com/photos/dpphotoieper/8726240030</p>
{% endblock %}

ownWebsite/templates/ownWebsite/Index.html
{% extends "ownWebsite/base.html" %}
{% load static %}

{% block title %}Blog{% endblock %}

{% block content %}
<img id="opener" 
     src="{% static "ownWebsite/Kamera.jpg" %}" 
     alt="kameraSelbstportrait">
{% endblock %}

ownWebsite/templates/ownWebsite/Projects.html
{% extends "ownWebsite/base.html" %}

{% block title %}Projects{% endblock %}

{% block content %}
<h3>Here are some of my sideprojects</h3>
<div id="catify-description">
  <span id="catify-text"><strong>Catify</strong> Replaces all images on a webside with cat images. Just drag and drop it to your bookmarks, to try it out on any website.</span>
  <a id="catify" source="https://www.flickr.com/photos/dpphotoieper/8726240030" href="javascript:var%20i=0,h=0,w=0,t=0,tmp=0;function%20getLink(height,width){return'http://placekitten.com/g/'+height+'/'+width};function%20sleep(milliseconds){var%20start=new Date().getTime();for(var i=0;i<1e7;i++){if((new%20Date().getTime()-start)>milliseconds){break}}}t=document.body.getElementsByTagName('img');for(i=0;i<t.length;i++){h=t[i].height;w=t[i].width;if(h>0&&w>0){t[i].src=getLink(w,h);sleep(0.01)}}function%20replaceImages(array){for(i=0;i<array.length;i++){if(document.defaultView.getComputedStyle(array[i]).backgroundImage!='none'){tmp=document.defaultView.getComputedStyle(array[i]);h=~~tmp.height.slice(0,-2);w=~~tmp.width.slice(0,-2);t[i].setAttribute('style','background-image:%20url('+getLink(h,w)+');background-position:initial');sleep(0.01)}}}t=document.getElementsByTagName('a');replaceImages(t);t=document.getElementsByTagName('div');replaceImages(t);t=document.getElementsByTagName('li');replaceImages(t);">
  </a>
</div>
<div id="textify-description">
  <span id="textify-text"><strong>Textify</strong> Replaces all text on a website by X. Just drag and drop it to your bookmarks, to try it out on any website.</span>
  <a id="textify" href="javascript:function walkTheDOM(node,func){func(node);node=node.firstChild;while(node){walkTheDOM(node,func);node = node.nextSibling;}}walkTheDOM(document.body,function(node){if(node.nodeType==3){if(/\S/.test(node.textContent)){for(var i=0,e='';i<node.textContent.length;i++){if(/\S/.test(node.textContent.charAt(i))){e+='x';}else{e+=' ';}}node.textContent=e;}}});"></a>
</div>
{% endblock %}

ownWebsite/templates/ownWebsite/Travel.html
{% extends "ownWebsite/base.html" %}

{% block title %}Travel{% endblock %}

{% block content %}
<h3>Under Construction</h3>
{% endblock %}

ownWebsite/templates/ownWebsite/base.html
{% load staticfiles ownWebsiteHelper%}
<html>
<head>
  <meta charset="UTF-8">
  <title>{% block title %}Adrian Bartnik{% endblock %}</title>
  <meta http-equiv="content-type" content="text/html; charset=UTF-8" />
  <link rel="shortcut icon" type="image/x-icon" href="{% static "ownWebsite/style.css" %}">
  <link rel="stylesheet" type="text/css" href="{% static "ownWebsite/style.css" %}">
  {% block imports %}{% endblock %}
</head>
<body>
  <div id="content">
    <div id="sidebar">
      <ul id="sidebar-content">
        <li><a href="{% url 'ownWebsite:aboutme' %}">About me</a></li>
        <li><a href="{% url 'ownWebsite:projects' %}">Ideas and Projects</a></li>
        <li><a href="{% url 'ownWebsite:travel' %}">Travel</a></li>
        <li><a href="{% url 'ownWebsite:blog' %}">Blog</a></li>
        <li><a href="{% url 'ownWebsite:impressum' %}">Impressum</a></li>
      </ul>
    </div>
    <div id='right'>
      <div id="block">
        <img id="headerimage" 
             src="{% random_image 'ownWebsite/HeaderImages/' %}"
             alt="NuuksioNationalPark">
        <div id="realContent">
          {% block content %}{% endblock %}
        </div>
      </div>
    </div>
  </div>
</body>
</html>